/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

// Configure Stream 0 for memory-to-peripheral transfer:
    // Channel selection (CHSEL=1)
void DMA_Stream_Config(
    DMA_TypeDef *DMAx,
    uint8_t stream_num,
    uint32_t direction,      // Memory-to-peripheral, peripheral-to-memory, etc.
    uint32_t peripheral_addr,
    uint32_t memory_addr,
    uint32_t data_length,
    uint32_t priority,      // Low, Medium, High, Very High
    uint32_t mem_inc,       // Memory increment (ENABLE/DISABLE)
    uint32_t periph_inc,    // Peripheral increment (ENABLE/DISABLE)
    uint32_t mem_size,      // 8-bit, 16-bit, 32-bit
    uint32_t periph_size,   // 8-bit, 16-bit, 32-bit
    uint32_t circular_mode  // ENABLE/DISABLE
) {
    DMA_Stream_TypeDef *stream = &DMAx->Stream[stream_num];

    // Disable the stream before configuration
    stream->CR &= ~DMA_SxCR_EN;

    // Clear all interrupt flags for this stream
    if (stream_num < 4) {
        DMAx->LIFCR = (0x3D << (6 * stream_num));  // Clear TCIF, HTIF, TEIF, DMEIF, FEIF
    } else {
        DMAx->HIFCR = (0x3D << (6 * (stream_num - 4)));
    }

    // Configure DMA_SxCR register
    stream->CR =
        (direction << DMA_SxCR_DIR_Pos) |
        (priority << DMA_SxCR_PL_Pos) |
        (mem_size << DMA_SxCR_MSIZE_Pos) |
        (periph_size << DMA_SxCR_PSIZE_Pos) |
        (mem_inc ? DMA_SxCR_MINC : 0) |
        (periph_inc ? DMA_SxCR_PINC : 0) |
        (circular_mode ? DMA_SxCR_CIRC : 0) |
        DMA_SxCR_TCIE;  // Enable Transfer Complete Interrupt (optional)

    // Set addresses and data length
    stream->PAR = peripheral_addr;
    stream->M0AR = memory_addr;
    stream->NDTR = data_length;

    // Enable FIFO mode (if needed, adjust FCR settings)
    stream->FCR = (1 << DMA_SxFCR_DMDIS_Pos) |  // Disable Direct Mode
                  (0x3 << DMA_SxFCR_FTH_Pos);   // FIFO threshold: 1/2 full
}
